### ISSUE TITLE
Milestone steps

### ISSUE THREAD

**Issue by PoisWu** [eti-demos/supplychan-security-tekton#1]
- [x] Create a kind cluster
- [x] Add a setup.sh file
    - [x] Customize `cosgin` installation based on different OS
        Support 
        - MacOS (brew) 
        - [x] linux
    - Install crane
    - Install tkn Tekton CLI
- [x] Deploy the tekton chain 
- [x] cosign function for the keygeneration
- [x] Import The Task and pipeline
- [x] Config the parameters, pull from the public github repo and push to ttl.sh 
- [x] Verify the signing agaist the signing key. 
- [x] Copy from the projet PRIM report to README.md
